import { type LeaseRecord } from './api';

export function exportToCSV(data: any[], columns: { header: string; accessor: string }[], filename: string) {
  const headers = columns.map(c => c.header).join(',');
  const rows = data.map(row => {
    return columns.map(col => {
      let val = col.accessor.split('.').reduce((o: any, k: string) => o?.[k], row);
      if (val === null || val === undefined) val = '';
      val = String(val).replace(/"/g, '""');
      return `"${val}"`;
    }).join(',');
  });

  const csv = [headers, ...rows].join('\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, `${filename}.csv`);
}

export function exportToPDF(data: any[], columns: { header: string; accessor: string }[], filename: string, title: string) {
  // Build a styled HTML table and print to PDF
  const headerRow = columns.map(c => `<th style="padding:8px 12px;background:#00325B;color:white;font-size:11px;text-align:left;border:1px solid #1a4a7a;">${c.header}</th>`).join('');
  
  const bodyRows = data.map((row, i) => {
    const bgColor = i % 2 === 0 ? '#ffffff' : '#f8f9fa';
    const cells = columns.map(col => {
      let val = col.accessor.split('.').reduce((o: any, k: string) => o?.[k], row);
      if (val === null || val === undefined) val = '—';
      return `<td style="padding:6px 12px;font-size:11px;border:1px solid #e5e7eb;background:${bgColor};">${val}</td>`;
    }).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; }
        h1 { color: #00325B; font-size: 18px; margin-bottom: 4px; }
        .subtitle { color: #6B7280; font-size: 12px; margin-bottom: 20px; }
        table { border-collapse: collapse; width: 100%; }
        .footer { margin-top: 20px; color: #9CA3AF; font-size: 10px; text-align: center; }
      </style>
    </head>
    <body>
      <h1>SQB iABS — ${title}</h1>
      <p class="subtitle">Generated on ${new Date().toLocaleString()} • ${data.length} records</p>
      <table>
        <thead><tr>${headerRow}</tr></thead>
        <tbody>${bodyRows}</tbody>
      </table>
      <p class="footer">This document was generated by iABS Demo #BuildWithAI</p>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 300);
  }
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
